version: 0.0
os: linux
#permissions:
#  - object: src/scripts
#    pattern: "*.sh"
#    owner: root
#    mode: 700
#    type:
#      - file
hooks:
  AfterInstall:
    - location: src/scripts/update.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: src/scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: src/scripts/stop.sh
      timeout: 300
      runas: root
