version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/update.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: src/scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: src/scripts/stop.sh
      timeout: 300
      runas: root
