version: 0.0
os: linux
files:
  - source: src/index.html
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: src/scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: src/scripts/stop.sh
      timeout: 300
      runas: root
