version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ls -al src/scripts/
      - chmod +x src/scripts/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - src/**/*
